///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

  // ✅ FIXED: Added missing namespace



/*
 * Caption
 * Text
 * Shell
 * 	Text
 * 
 * 
 * */

// elementCount : 317 

namespace Izzet_Test_V1
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public static void Main()
        {
        	string save_to_txt = @"C:\Users\mirsad\Desktop\Izzet\UIElements.txt";
         	string basePath = repo.AselsanKardelen.AbsoluteBasePath.ToString();
         	
         	try
            {
                string targetPath = basePath +"/container[1]//container[@caption='CBS']/?/?/form[@title='']/picture[@name='canvas0']";
                Report.Info($"Searching for element: {targetPath}");
                
                Unknown targetElement = Host.Local.FindSingle<Unknown>(targetPath, 5000);
                
                if (targetElement != null)
                {
                    targetElement.Click(); // Click the element
                    Report.Info("Element found and clicked successfully.");
                    
                    // Take and save an image of the element
                    Imaging.CaptureImage(targetElement.Element).Save($"C:\\Users\\mirsad\\Desktop\\Izzet\\CapturedElement.png");
                    Report.Info("Element image captured and saved.");
                }
                else
                {
                    Report.Warn("Target element not found!");
                }
            }
            catch (Exception ex)
            {
                Report.Error($"An error occurred: {ex.Message}");
            }

		}

    }
}
